import path from 'path';
import { execa } from 'execa';
import { ProjectOptions } from '../types';
import { logger } from '../utils/logger';
import {
  ensureDir,
  writeFile,
} from '../utils/fs-utils';
import {
  detectPackageManager,
  getInstallCommand,
  PackageManager,
} from '../utils/package-manager';
import { ConfigGenerator } from './config-generator';
import { validateProjectMode } from '../validators/mode-validator';
import { setupNext16Features } from './next16-setup';
import { setupSeniorConfig } from './senior-setup';

export abstract class BaseGenerator {
  protected projectPath: string;
  protected options: ProjectOptions;
  protected packageManager: PackageManager;

  constructor(options: ProjectOptions) {
    this.options = options;
    this.projectPath = path.resolve(process.cwd(), options.path || options.name);
    this.packageManager = detectPackageManager();
  }

  async generate(): Promise<void> {
    try {
      logger.startSpinner('Creating project structure...');
      await this.createProjectStructure();
      logger.succeedSpinner('Project structure created');

      logger.startSpinner('Generating configuration files...');
      await this.generateConfigFiles();
      logger.succeedSpinner('Configuration files generated');

      logger.startSpinner('Creating NextCraft configuration...');
      await this.generateNextCraftConfig();
      logger.succeedSpinner('NextCraft configuration created');

      logger.startSpinner('Setting up base dependencies...');
      await this.setupBaseDependencies();
      logger.succeedSpinner('Base dependencies configured');

      logger.startSpinner('Creating UI components...');
      await this.setupUI();
      logger.succeedSpinner('UI components created');

      if (this.options.seo) {
        logger.startSpinner('Setting up SEO...');
        await this.setupSEO();
        logger.succeedSpinner('SEO configured');
      }

      if (this.options.rtl) {
        logger.startSpinner('Enabling RTL support...');
        await this.setupRTL();
        logger.succeedSpinner('RTL support enabled');
      }

      await this.customSetup();

      logger.startSpinner('Setting up Next.js 16 features...');
      await this.setupNext16();
      logger.succeedSpinner('Next.js 16 features configured');

      logger.startSpinner('Configuring Senior-Level standards...');
      await this.setupSeniorStandards();
      logger.succeedSpinner('Senior-Level standards configured');

      logger.startSpinner('Installing dependencies...');
      await this.installDependencies();
      logger.succeedSpinner('Dependencies installed');

      logger.startSpinner('Initializing git repository...');
      await this.initGit();
      logger.succeedSpinner('Git repository initialized');

      logger.startSpinner('Validating project structure...');
      await this.validateProject();
      logger.succeedSpinner('Project validation completed');

      this.printSuccessMessage();
    } catch (error) {
      logger.failSpinner('Failed to generate project');
      throw error;
    }
  }

  protected abstract createProjectStructure(): Promise<void>;
  protected abstract setupBaseDependencies(): Promise<void>;
  protected abstract customSetup(): Promise<void>;

  protected async generateConfigFiles(): Promise<void> {
    // package.json
    const packageJson = {
      name: this.options.name,
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
      },
      dependencies: {},
      devDependencies: {},
    };

    await writeFile(
      path.join(this.projectPath, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    // tsconfig.json
    const tsConfig = {
      compilerOptions: {
        target: 'ES2020',
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        jsx: 'preserve',
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        allowJs: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        incremental: true,
        paths: {
          '@/*': ['./src/*'],
        },
        plugins: [{ name: 'next' }],
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    };

    await writeFile(
      path.join(this.projectPath, 'tsconfig.json'),
      JSON.stringify(tsConfig, null, 2)
    );

    // next.config.ts - Next.js 16 optimized
    const nextConfig = `import type { NextConfig } from 'next'

/**
 * Next.js 16 Configuration
 * Generated by NextCraft with optimized settings
 * 
 * @see https://nextjs.org/docs/app/api-reference/next-config-js
 */
const nextConfig: NextConfig = {
  // Enable React Strict Mode for better development experience
  reactStrictMode: true,
  
  // Next.js 16 - Cache Components (enables Partial Prerendering)
  cacheComponents: true,
  
  // Image Optimization
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      // Add your image domains here
      // {
      //   protocol: 'https',
      //   hostname: 'example.com',
      // }
    ]
  },
  
  // TypeScript
  typescript: {
    // Type checking during build
    ignoreBuildErrors: false
  },
  
  // Headers for security
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          {
            key: 'X-DNS-Prefetch-Control',
            value: 'on'
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN'
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff'
          }
        ]
      }
    ]
  }
}

export default nextConfig
`;

    await writeFile(path.join(this.projectPath, 'next.config.ts'), nextConfig);

    // .gitignore
    const gitignore = `node_modules/
.next/
out/
.env*.local
.DS_Store
*.log
`;

    await writeFile(path.join(this.projectPath, '.gitignore'), gitignore);

    // .env.example
    await writeFile(path.join(this.projectPath, '.env.example'), '# Environment variables\n');

    // README.md
    const readme = `# ${this.options.name}

Created with NextCraft 🚀

## Getting Started

\`\`\`bash
${this.packageManager} dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000)
`;

    await writeFile(path.join(this.projectPath, 'README.md'), readme);
  }

  protected async setupUI(): Promise<void> {
    if (this.options.ui === 'shadcn') {
      await this.setupShadcnUI();
    }
  }

  protected async setupShadcnUI(): Promise<void> {
    // components.json for shadcn
    const componentsConfig = {
      $schema: 'https://ui.shadcn.com/schema.json',
      style: 'default',
      rsc: true,
      tsx: true,
      tailwind: {
        config: 'tailwind.config.ts',
        css: 'src/app/globals.css',
        baseColor: 'slate',
        cssVariables: true,
      },
      aliases: {
        components: '@/components',
        utils: '@/lib/utils',
      },
    };

    await writeFile(
      path.join(this.projectPath, 'components.json'),
      JSON.stringify(componentsConfig, null, 2)
    );

    // Tailwind config (using JS for better compatibility)
    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('tailwindcss-animate')],
}
`;

    await writeFile(path.join(this.projectPath, 'tailwind.config.js'), tailwindConfig);

    // PostCSS config (TailwindCSS 4)
    const postcssConfig = `module.exports = {
  plugins: {
    '@tailwindcss/postcss': {},
  },
}
`;

    await writeFile(path.join(this.projectPath, 'postcss.config.js'), postcssConfig);

    // Global CSS (TailwindCSS 4 compatible)
    const globalCSS = `@import "tailwindcss";

* {
  border-color: hsl(var(--border));
}

body {
  background-color: hsl(var(--background));
  color: hsl(var(--foreground));
  font-family: system-ui, -apple-system, sans-serif;
}

@theme {
  --color-background: 0 0% 100%;
  --color-foreground: 222.2 84% 4.9%;
  --color-card: 0 0% 100%;
  --color-card-foreground: 222.2 84% 4.9%;
  --color-popover: 0 0% 100%;
  --color-popover-foreground: 222.2 84% 4.9%;
  --color-primary: 222.2 47.4% 11.2%;
  --color-primary-foreground: 210 40% 98%;
  --color-secondary: 210 40% 96.1%;
  --color-secondary-foreground: 222.2 47.4% 11.2%;
  --color-muted: 210 40% 96.1%;
  --color-muted-foreground: 215.4 16.3% 46.9%;
  --color-accent: 210 40% 96.1%;
  --color-accent-foreground: 222.2 47.4% 11.2%;
  --color-destructive: 0 84.2% 60.2%;
  --color-destructive-foreground: 210 40% 98%;
  --color-border: 214.3 31.8% 91.4%;
  --color-input: 214.3 31.8% 91.4%;
  --color-ring: 222.2 84% 4.9%;
  
  --radius-sm: 0.25rem;
  --radius-md: 0.5rem;
  --radius-lg: 1rem;
}
`;

    await ensureDir(path.join(this.projectPath, 'src', 'app'));
    await writeFile(path.join(this.projectPath, 'src', 'app', 'globals.css'), globalCSS);

    // lib/utils.ts
    const utils = `import { type ClassValue, clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`;

    await ensureDir(path.join(this.projectPath, 'src', 'lib'));
    await writeFile(path.join(this.projectPath, 'src', 'lib', 'utils.ts'), utils);
  }

  protected async setupSEO(): Promise<void> {
    // SEO config
    const seoConfig = `export const siteConfig = {
  name: '${this.options.name}',
  description: 'Built with NextCraft',
  url: 'https://${this.options.name}.com',
  ogImage: 'https://${this.options.name}.com/og.jpg',
  links: {
    twitter: 'https://twitter.com/${this.options.name}',
    github: 'https://github.com/${this.options.name}',
  },
}

export type SiteConfig = typeof siteConfig
`;

    await ensureDir(path.join(this.projectPath, 'src', 'config'));
    await writeFile(path.join(this.projectPath, 'src', 'config', 'site.ts'), seoConfig);
  }

  protected async setupRTL(): Promise<void> {
    // Will be implemented with specific RTL utilities
  }

  protected async generateNextCraftConfig(): Promise<void> {
    const configGenerator = new ConfigGenerator(this.projectPath, this.options);
    await configGenerator.generate();
  }

  protected async validateProject(): Promise<void> {
    const isValid = await validateProjectMode(this.projectPath);
    if (!isValid) {
      logger.warn('⚠ Project validation found some issues (non-critical)');
    }
  }

  protected async setupNext16(): Promise<void> {
    await setupNext16Features(this.projectPath);
  }

  protected async setupSeniorStandards(): Promise<void> {
    await setupSeniorConfig(this.projectPath);
  }

  protected async installDependencies(): Promise<void> {
    await execa(this.packageManager, ['install'], {
      cwd: this.projectPath,
      stdio: 'inherit',
    });
  }

  protected async initGit(): Promise<void> {
    try {
      await execa('git', ['init'], { cwd: this.projectPath });
      await execa('git', ['add', '.'], { cwd: this.projectPath });
      await execa('git', ['commit', '-m', 'Initial commit from NextCraft'], {
        cwd: this.projectPath,
      });
    } catch {
      // Git init failed, skip
    }
  }

  protected printSuccessMessage(): void {
    logger.newLine();
    logger.box(
      `✨ Project ${this.options.name} created successfully!\n\n` +
        `📁 Location: ${this.projectPath}\n` +
        `🚀 Mode: ${this.options.mode}\n` +
        `🎨 UI: ${this.options.ui}\n\n` +
        `Next steps:\n` +
        `  cd ${this.options.name}\n` +
        `  ${getInstallCommand(this.packageManager)}\n` +
        `  ${this.packageManager} dev`
    );
  }
}
